title: Sana ur Rehman Arain
logo: /assets/img/headshot_circle.PNG
description: Data science enthusiast with experience in Python, R, and business analytics.
# show_downloads: true
theme: jekyll-theme-minimal
